name: Code Formatting Workflow using Prettier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Format with Prettier
        run: npx prettier --write .

      - name: Commit changes
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"
          git commit -a -m "Automated code formatting with Prettier [skip ci]"
          git push
