name: Scheduled Backups Workflow

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create backup
        run: |
          mkdir -p backups
          zip -r backups/backup-$(date +%Y-%m-%d-%H-%M-%S).zip .
      - name: Upload backup to releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./backups/backup-$(date +%Y-%m-%d-%H-%M-%S).zip
          asset_name: backup-$(date +%Y-%m-%d-%H-%M-%S).zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
